version: '3'
services:
  nginx:
    image: hungvietgiang/nginx-centos7:v1
    container_name: ${NAME_CONTAINER}_nginx
    restart: always
    ports:
      - "${PORTS_NGINX}:80"
    expose:
      - "80"
    stdin_open: true
    tty: true
    volumes:
      - ./:/var/home/
      - .docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    command: nginx

  php-fpm:
    image: hungvietgiang/php74-centos7:1.2
    container_name: ${NAME_CONTAINER}_php-fpm
    restart: always
    expose:
      - "9000"
    volumes:
      - ./:/var/home:cached
      - .docker/php-fpm/php-fpm.conf:/etc/php-fpm.conf
      - .docker/php-fpm/www.conf:/etc/php-fpm.d/www.conf
      - .docker/php-fpm/php.ini:/etc/php.ini
    stdin_open: true
    tty: true
    command: php-fpm

  mysqldb:
    image: mysql:5.7
    container_name: ${NAME_CONTAINER}_mysql
    restart: always
    environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
        - "${PORTS_MYSQL}:3306"
    tty: true
    volumes:
      - ./.docker/mysql/database:/var/lib/minesql

  # elastic search
  elasticsearch:
    container_name: ${NAME_CONTAINER}_es-single
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./.docker/elasticsearch/data01:/usr/share/elasticsearch/data
    ports:
      - "${PORTS_ELASTICSEARCH}:9200"
      - 9300:9300

  # kibana
  kibana:
    container_name: ${NAME_CONTAINER}_kibana-single
    image: docker.elastic.co/kibana/kibana:7.15.1
    environment:
      - "ELASTICSEARCH_HOSTS=http://${NAME_CONTAINER}_es-single:${PORTS_ELASTICSEARCH}"
    ports:
      - ${PORTS_ELASTICSEARCH}:5601
    depends_on:
      - elasticsearch
